Add safe abstractions to CRC functions in ESP ROM
esp-rs/esp-idf-hal pull request #261
Opened 2023-06-10 04:08 UTC by jordanhalase

This is the safe CRC abstraction over the newly merged esp-rs/esp-idf-sys@4ffb8838c8bb9e76c43ca021fdb9b5050340d036

I created the `rom` module to put commonly available ROM libraries, such as CRC. MD5 could be next.

Test code is below or at [my repository](https://github.com/jordanhalase/test-esp-idf-hal-crc/blob/master/src/main.rs)

```Rust
use esp_idf_sys as _; // For binstart

use esp_idf_hal::rom::crc;

fn main() {
    esp_idf_sys::link_patches();

    let data = "123456789";

    loop {
        let crc_hdlc = crc::crc32_le(!0xffffffff, data.as_ref());
        let crc_bzip2 = crc::crc32_be(!0xffffffff, data.as_ref());
        let crc_mpeg2 = !crc::crc32_be(!0xffffffff, data.as_ref());
        let crc_cksum = crc::crc32_be(!0, data.as_ref());
        let crc_kermit = !crc::crc16_le(!0, data.as_ref());
        let crc_genibus = crc::crc16_be(!0xffff, data.as_ref());
        let crc_rohc = !crc::crc8_le(!0xff, data.as_ref());
        let crc_smbus = !crc::crc8_be(!0, data.as_ref());

        assert_eq!(crc_hdlc, 0xcbf43926);
        assert_eq!(crc_bzip2, 0xfc891918);
        assert_eq!(crc_mpeg2, 0x0376e6e7);
        assert_eq!(crc_cksum, 0x765e7680);
        assert_eq!(crc_kermit, 0x2189);
        assert_eq!(crc_genibus, 0xd64e);
        assert_eq!(crc_rohc, 0xd0);
        assert_eq!(crc_smbus, 0xf4);

        println!("{:08x} {:08x} {:08x} {:08x} {:04x} {:04x} {:02x} {:02x}",
            crc_hdlc, crc_bzip2, crc_mpeg2, crc_cksum, crc_kermit, crc_genibus, crc_rohc, crc_smbus);

        std::thread::sleep(std::time::Duration::from_millis(5000));
    }
}
```

2023-06-10 12:02 UTC, Vollbrecht requested changes
Thank you for the contribution :heart:

2023-06-10 13:32 UTC, jordanhalase commented on src/rom/mod.rs
> +pub mod crc;
Physically it's in the ROM of all the ESP chips going all the way back to the original ESP32.

For extra measure I checked the [v4.3 release branch](https://github.com/espressif/esp-idf/tree/release/v4.3/components/esp_rom) and the [current master branch](https://github.com/espressif/esp-idf/tree/master/components/esp_rom) and I see all the symbols there. In fact, the CRC files haven't been touched in three years.

Some chips may not have all these functions in physical ROM, but any missing functions will be compiled into the program binary automatically. (Default implementation in [patches/esp_crc_rom.c](https://github.com/espressif/esp-idf/blob/master/components/esp_rom/patches/esp_rom_crc.c))

2023-06-10 13:39 UTC, jordanhalase commented on src/lib.rs
> +pub mod rom;
Done. I put it in lib.rs for all ROM functions.

2023-06-11 07:59 UTC, ivmarkov commented
@jordanhalase Can you run `cargo fmt` on your PR and update? Also, please run `cargo clippy` as well, as that's the next step after `fmt`.

2023-06-11 15:48 UTC, jordanhalase commented
Ran cargo fmt and clippy :)

2023-06-12 05:49 UTC, merged