Add CAN self reception Frame
esp-rs/esp-idf-hal pull request #411
Opened 2024-04-24 06:14 UTC by elotom

In my project, I'm using `Mode::NoAck` to self-test the CAN controller (loopback of transmissions) and self-reception frame.
This pull request adds a missing [self-reception frame](https://docs.espressif.com/projects/esp-idf/en/stable/esp32s3/api-reference/peripherals/twai.html#message-fields-and-flags).

2024-04-24 10:35 UTC, Vollbrecht requested changes

2024-04-24 10:35 UTC, Vollbrecht commented on src/can.rs
> +    pub fn new_self(id: u32, extended: bool, data: &[u8]) -> Option<Self> {
I am not to deep into CAN itself, though from an API perspective i am wondering, we would now create 3 different new methods that have basically the same structure and just depending on the "extended" bool would set a different value. Why do we not combine them into one method that takes a enum representing all 3 cases?

2024-04-27 11:59 UTC, Vollbrecht commented
I think i am fine with how it is, though i just want to hear your opinions on the "Flag" naming of the enum. Since we have all can stuff in one module, is the "Flag" name for the enum a bit to general? - e.g can it be confused easily with other CAN related stuff.
Is there an already established term for this kind of variants out there? For me it could also be called something like "FrameType" or "MessageType" or something? So the enum has a bit more association to what it represents.

2024-04-30 04:21 UTC, ivmarkov commented
I think the PR is in a good shape - clean and tidy even if we have some concern about the naming, so we should not delay it any further.

Merging.

2024-04-30 04:21 UTC, merged