Keep all SPI sub-operations within a single transaction
esp-rs/esp-idf-hal pull request #50
Opened 2022-03-11 22:37 UTC by Dominaezzz

Starts to address #48 .

This makes sure that calls to `transfer`, `write`, `read` and `transfer_inplace` regardless of how big the given buffer is happens within a single transaction. Users who wish to break up their transactions can easily do so themselves by calling these operations multiple times.

This doesn't fix `exec` yet as I want to start small.

2022-03-11 22:56 UTC, Dominaezzz commented
Not sure why `SPI_TRANS_CS_KEEP_ACTIVE` can't be found.
My first guess is that it's because it's a `#define` but the suggested alternative is also a `#define`.
(I'm new to bindgen and Rust in general)

2022-03-12 17:28 UTC, Dominaezzz commented
I just realised the `SPI_TRANS_CS_KEEP_ACTIVE` is a ESP_IDF=4.4 feature....

2022-03-13 18:53 UTC, ivmarkov commented
You can still implement it with conditional compilation of esp idf >= esp idf v4.4

2022-03-13 18:55 UTC, Dominaezzz commented
I have but how do I get around the unused variable it might leave behind.

Also, are there any plans to make esp-idf 4.4 a min dep?

2022-03-14 17:49 UTC, ivmarkov requested changes
Overall, looks OK. Two small nits, and one very important question :)

2022-03-14 17:49 UTC, ivmarkov commented on src/spi.rs
> +        #[cfg(any(esp_idf_version = "4.4", esp_idf_version_major = "5"))]
Can you turn this check into !V4.3?
I.e. something like `#[cfg(not(esp_idf_version = "4.3"))]`

This way, if this code is still around when ESP-IDF V6 is released, it won't break (and we don't support ESP-IDF releases < 4.3).

2022-03-14 17:49 UTC, ivmarkov commented on src/spi.rs
> +            let is_last_chunk;
Nit: you can just do `let is_last_chunk = if ...`. Will shorten the code a bit.

2022-03-14 17:49 UTC, ivmarkov commented on src/spi.rs
> +            let is_last_chunk = offset + TRANS_LEN < len;
Most important question: is the API of `embedded-hal` mandating that all transfers not using the `Transaction` traits should still be in a single transaction? I.e., if I do an innocent long `write`, it should be in a single transaction?

2022-03-14 23:23 UTC, Dominaezzz commented on src/spi.rs
> +            let is_last_chunk = offset + TRANS_LEN < len;
I don't see anything mandating this in the `embedded-hal` API, so technically this isn't strictly breaking contract.
However, I've got some justifications.
- I'm using this to talk to an epaper driver IT8951 and it requires every transaction to have some preamble bits. I spent a few hours wondering why my code wasn't working until I came to look at the source code here. I've now ended up keeping my `write`s and `read`s < 32 to make sure I'm in a single transaction. It's a bit awkward to be breaking up my transfers when the library I'm using is also doing the same thing.
- The next version of `embedded-hal` will be enforcing this. https://github.com/rust-embedded/embedded-hal/blob/b5c29b39880e467ef65ceb5534422d0e58539119/src/spi/blocking.rs . Everything has now been written in terms of transactions.

2022-03-15 12:38 UTC, Dominaezzz commented on src/spi.rs
> +            let is_last_chunk = offset + TRANS_LEN < len;
Well, with DMA it can do more than 64 bytes but it's been disabled in here for some reason. Of course, I do appreciate that some people might want to disable DMA, which brings us back.

I've already given that some thought. I've also thought about how DMA might fit into it since it's something I really want.
Would it be alright if I pinged you on Matrix?

2022-03-17 23:30 UTC, Dominaezzz commented on src/spi.rs
> +            let is_last_chunk = offset + TRANS_LEN < len;
The SpiBus trait can't be easily implemented in terms of esp-idf's spi interface, since you need a device to perform transactions but the SpiDevice can be.

2022-03-18 12:43 UTC, ivmarkov commented on src/spi.rs
> +            let is_last_chunk = offset + TRANS_LEN < len;
Why can't the SpiBus trait be emulated with a device plus optionally bus locking?

2022-03-18 12:46 UTC, ivmarkov commented on src/spi.rs
> +            let is_last_chunk = offset + TRANS_LEN < len;
I mean, at the moment, what we have with the e-hal 0.2 is essentially only the notion of an spi bus and we emulate it that way.

2022-03-18 12:55 UTC, Dominaezzz commented on src/spi.rs
> +            let is_last_chunk = offset + TRANS_LEN < len;
Yes it can indeed be emulated with a lock lasting the duration of the SpiBus trait lifetime. It just felt a bit kludgy at first.

2022-03-18 22:16 UTC, Dominaezzz commented on src/spi.rs
> +            let is_last_chunk = offset + TRANS_LEN < len;
Pulling out the Bus from `Master` will mean breaking changes. Is that acceptable?

2022-03-19 09:45 UTC, ivmarkov commented on src/spi.rs
> +            let is_last_chunk = offset + TRANS_LEN < len;
Yes. Not nice but we are at 0.X, so that's okay. And, most of the user code should be coded against the 0.2 e-hal traits anyway. It is the initialization of the SPI driver that might break.

If you have cycles, let's try to explore the path and once we have concrete code, then actually we can say how much and what would break.

2022-03-19 12:24 UTC, Dominaezzz commented on src/spi.rs
> +            let is_last_chunk = offset + TRANS_LEN < len;
POC: https://github.com/esp-rs/esp-idf-hal/pull/52

2022-04-17 07:28 UTC, ivmarkov commented
Obsoleted by https://github.com/esp-rs/esp-idf-hal/pull/61

2022-04-17 07:28 UTC, closed without merging